blockExoticSubdeps: true

strictDepBuilds: true
allowBuilds:
  "@swc/core": true
  core-js-pure: true
  core-js: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 20080
# trustPolicyExclude:
#   - "detect-port@1.6.1"
#   - "semver@6.3.1"
#   - "@swc/core"
#   - "undici-types@6.20.0"
#   - "langium@3.3.1"
